### ISSUE TITLE
ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialize

### ISSUE THREAD

**Issue by farr64** [mohamedHassanKa/flutter_internationalization#3]
Thanks for looking into this:

E/flutter (18957): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: ServicesBinding.defaultBinaryMessenger was accessed before the binding was initialized.
E/flutter (18957): If you're running an application and need to access the binary messenger before `runApp()` has been called (for example, during plugin initialization), then you need to explicitly call the `WidgetsFlutterBinding.ensureInitialized()` first.
E/flutter (18957): If you're running a test, you can call the `TestWidgetsFlutterBinding.ensureInitialized()` as the first line in your test's `main()` method to initialize the binding.
E/flutter (18957): #0      defaultBinaryMessenger.<anonymous closure> (package:flutter/src/services/binary_messenger.dart:76:7)
E/flutter (18957): #1      defaultBinaryMessenger (package:flutter/src/services/binary_messenger.dart:89:4)
E/flutter (18957): #2      MethodChannel.binaryMessenger (package:flutter/src/services/platform_channel.dart:140:62)
E/flutter (18957): #3      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:314:35)
E/flutter (18957): #4      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:349:48)
E/flutter (18957): #5      MethodChannelSharedPreferencesStore.getAll (package:shared_preferences_platform_interface/method_channel_shared_preferences.dart:54:22)
E/flutter (18957): #6      SharedPreferences._getSharedPreferencesMap (package:shared_preferences/shared_preferences.dart:166:57)
E/flutter (18957): #7      SharedPreferences.getInstance (package:shared_preferences/shared_preferences.dart:33:19)
E/flutter (18957): #8      AppLanguage.fetchLocale (package:flutter_internationalizationn/AppLanguage.dart:9:41)
E/flutter (18957): #9      main (package:flutter_internationalizationn/main.dart:10:21)
E/flutter (18957): #10     _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:239:25)
E/flutter (18957): #11     _rootRun (dart:async/zone.dart:1126:13)
E/flutter (18957): #12     _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter (18957): #13     _runZoned (dart:async/zone.dart:1518:10)
E/flutter (18957): #14     runZoned (dart:async/zone.dart:1502:12)
E/flutter (18957): #15     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:231:5)
E/flutter (18957): #16     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:307:19)
E/flutter (18957): #17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)
E/flutter (18957): 
Debug service listening on ws://127.0.0.1:50501/E7T71TcRV-0=/ws

**Comment by Sankaranis** [comment]
Try this code. It's working fine
 provider: ^4.0.5


void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  AppLanguage appLanguage = AppLanguage();
  await appLanguage.fetchLocale();
  runApp(MyApp(
    appLanguage: appLanguage,
  ));
}

 @override
  Widget build(BuildContext context) {
    return ChangeNotifierProvider<AppLanguage>(
      create: (_) => appLanguage,
      child: Consumer<AppLanguage>(builder: (context, model, child) {
        return MaterialApp(
          locale: model.appLocal,
          supportedLocales: [
            Locale('en', 'US'),
            Locale('ar', ''),
          ],
          localizationsDelegates: [
            AppLocalizations.delegate,
            GlobalMaterialLocalizations.delegate,
            GlobalWidgetsLocalizations.delegate,
          ],
          home: AppLang(),
        );
      }),
    );
  }
